"use client";

import { useEffect, useRef, useState } from "react";
import { Archive, ChevronLeft, Inbox, Mail, Plus, Search, Send, Settings, ShieldCheck, X } from "lucide-react";

type Thread = { id: string; subject: string; receivingAlias: string; isUnread: boolean; lastMessageAt: string; sender?: string | null; preview?: string | null };
type Message = { id: string; rfcMessageId?: string | null; references?: string | null; direction: "inbound" | "outbound"; status: string; fromAddress: string; toAddresses: string[]; textBody: string; sanitizedHtml: string; createdAt: string };
type Detail = { thread: Thread; messages: Message[] };

export function InboxShell() {
  const [threads, setThreads] = useState<Thread[]>([]);
  const [detail, setDetail] = useState<Detail | null>(null);
  const [composeNew, setComposeNew] = useState(false);
  const [mobileThread, setMobileThread] = useState(false);
  const [search, setSearch] = useState("");
  const [alias, setAlias] = useState("");
  const [showArchived, setShowArchived] = useState(false);
  const [loading, setLoading] = useState(true);
  useEffect(() => { void loadThreads(search, alias, showArchived); }, [search, alias, showArchived]);
  async function loadThreads(value: string, selectedAlias = alias, archived = showArchived) { setLoading(true); const params = new URLSearchParams({ search: value }); if (selectedAlias) params.set("alias", selectedAlias); if (archived) params.set("archived", "true"); const response = await fetch(`/api/admin/inbox?${params}`); if (response.ok) setThreads((await response.json() as { threads: Thread[] }).threads); setLoading(false); }
  async function openThread(thread: Thread) { const response = await fetch(`/api/admin/inbox/threads/${thread.id}`); if (response.ok) { setDetail(await response.json()); setComposeNew(false); setMobileThread(true); } }
  async function updateThread(threadId: string, action: "read" | "unread" | "archive" | "restore") { const response = await fetch(`/api/admin/inbox/threads/${threadId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action }) }); if (response.ok) { setDetail(null); setMobileThread(false); await loadThreads(search, alias, showArchived); } }
  return (
    <main className={`admin-inbox ${mobileThread ? "admin-mobile-thread" : ""}`}>
      <header className="admin-topbar"><div><p className="eyebrow">Fidexa / Workspace</p><h1>Inbox</h1></div><div className="admin-top-actions"><span className="admin-secure"><ShieldCheck size={14} /> Private workspace</span><button className="admin-icon-button" aria-label="Settings"><Settings size={18} /></button></div></header>
      <section className="admin-inbox-grid">
        <Sidebar alias={alias} archived={showArchived} onAlias={(selectedAlias) => { setAlias(selectedAlias); setShowArchived(false); setDetail(null); }} onArchived={() => { setShowArchived(true); setDetail(null); }} onCompose={() => { setDetail(null); setComposeNew(true); setMobileThread(true); }} />
        <section className="admin-thread-list"><div className="admin-list-header"><div><p className="eyebrow">All inboxes</p><h2>{threads.length} conversations</h2></div></div><label className="admin-search"><Search size={16} /><input aria-label="Search inbox" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search sender, subject, body" /></label><div className="admin-list-scroll">{loading ? <p className="admin-empty">Loading conversations…</p> : threads.length ? threads.map((thread) => <button className="admin-thread-row" key={thread.id} onClick={() => void openThread(thread)}><span className="admin-thread-dot" /><span className="admin-thread-copy"><span className="admin-thread-meta"><strong>{thread.sender || "Unknown sender"}</strong><time>{new Date(thread.lastMessageAt).toLocaleDateString()}</time></span><strong className="admin-thread-subject">{thread.subject}</strong><span className="admin-thread-preview">{thread.preview || "No preview"}</span></span></button>) : <div className="admin-empty"><Mail size={24} /><strong>Your inbox is clear.</strong><span>New mail to a Fidexa alias will appear here.</span></div>}</div></section>
        <section className="admin-thread-view">{composeNew ? <NewComposer fromAddress={alias || "hello@fidexa.org"} onClose={() => { setComposeNew(false); setMobileThread(false); }} /> : detail ? <ThreadView detail={detail} onAction={(action) => updateThread(detail.thread.id, action)} onBack={() => setMobileThread(false)} /> : <div className="admin-no-thread"><Mail size={36} /><h2>Select a conversation</h2><p>Choose a message from your inbox to read the full thread and reply.</p></div>}</section>
      </section>
    </main>
  );
}

function Sidebar({ alias, archived, onAlias, onArchived, onCompose }: { alias: string; archived: boolean; onAlias: (alias: string) => void; onArchived: () => void; onCompose: () => void }) { return <aside className="admin-rail"><div className="admin-brand-row"><span className="admin-brand-mark">f</span><span>FIDEXA</span></div><button className="admin-compose" onClick={onCompose}><Plus size={16} /> New message</button><p className="admin-rail-label">Mail</p><button className={`admin-folder ${!archived ? "admin-folder-active" : ""}`} onClick={() => onAlias("")}><Inbox size={16} /> Inbox</button><button className={`admin-folder ${archived ? "admin-folder-active" : ""}`} onClick={onArchived}><Archive size={16} /> Archived</button><p className="admin-rail-label">Aliases</p><button className={`admin-alias ${!alias && !archived ? "admin-alias-active" : ""}`} onClick={() => onAlias("")}><span className="admin-alias-dot" />All inboxes</button>{["hello@fidexa.org", "sales@fidexa.org", "support@fidexa.org", "info@fidexa.org", "faridmatovu@fidexa.org"].map((item) => <button className={`admin-alias ${alias === item && !archived ? "admin-alias-active" : ""}`} key={item} onClick={() => onAlias(item)}><span className="admin-alias-dot" />{item}</button>)}<div className="admin-rail-foot"><span className="admin-avatar">F</span><span><strong>Farid</strong><small>Administrator</small></span></div></aside>; }

function ThreadView({ detail, onAction, onBack }: { detail: Detail; onAction: (action: "read" | "unread" | "archive" | "restore") => Promise<void>; onBack: () => void }) {
  const [body, setBody] = useState(""); const [status, setStatus] = useState(""); const latest = detail.messages.at(-1); const draftId = useRef<string | undefined>(undefined); const sendKey = useRef<string | undefined>(undefined);
  useEffect(() => { let cancelled = false; void fetch(`/api/admin/inbox/drafts?threadId=${detail.thread.id}`).then(async (response) => response.ok ? await response.json() as { drafts: Array<{ id: string; textBody: string }> } : { drafts: [] }).then((data) => { const draft = data.drafts[0]; if (!cancelled && draft) { draftId.current = draft.id; setBody(draft.textBody); } }).catch(() => undefined); return () => { cancelled = true; }; }, [detail.thread.id]);
  useEffect(() => { if (!latest) return; const timer = window.setTimeout(async () => { const response = await fetch("/api/admin/inbox/drafts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: draftId.current, threadId: detail.thread.id, fromAddress: detail.thread.receivingAlias, toAddresses: [latest.fromAddress], subject: detail.thread.subject, textBody: body }) }); if (response.ok) { draftId.current = (await response.json() as { draft?: { id: string } }).draft?.id; setStatus("Draft saved"); } }, 700); return () => window.clearTimeout(timer); }, [body, detail.thread.id, detail.thread.receivingAlias, detail.thread.subject, latest]);
  async function send() { if (!body.trim() || !latest) return; sendKey.current ??= crypto.randomUUID(); setStatus("Sending…"); const response = await fetch("/api/admin/inbox/send", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idempotencyKey: sendKey.current, draftId: draftId.current ?? null, threadId: detail.thread.id, fromAddress: detail.thread.receivingAlias, to: latest.fromAddress, subject: `Re: ${detail.thread.subject}`, textBody: body, inReplyTo: latest.rfcMessageId ?? null, references: [latest.references, latest.rfcMessageId].filter(Boolean).join(" ") || null }) }); setStatus(response.ok ? "Sent" : "Could not send"); if (response.ok) { draftId.current = undefined; sendKey.current = undefined; setBody(""); } }
  return <div className="admin-thread-content"><div className="admin-thread-toolbar"><button className="admin-icon-button admin-mobile-only" aria-label="Back to conversations" onClick={onBack}><ChevronLeft size={18} /></button><div className="admin-toolbar-actions"><button onClick={() => void onAction(detail.thread.isUnread ? "read" : "unread")}>{detail.thread.isUnread ? "Mark read" : "Mark unread"}</button><button onClick={() => void onAction("archive")}><Archive size={15} /> Archive</button></div></div><div className="admin-thread-heading"><p className="eyebrow">{detail.thread.receivingAlias}</p><h2>{detail.thread.subject}</h2><p className="admin-muted">{detail.messages.length} messages in this conversation</p></div><div className="admin-message-stack">{detail.messages.map((message) => <article className="admin-message" key={message.id}><div className="admin-message-header"><span className="admin-avatar admin-avatar-small">{message.fromAddress[0]?.toUpperCase()}</span><div><strong>{message.fromAddress}</strong><small>to {message.toAddresses.join(", ")}</small></div><time>{new Date(message.createdAt).toLocaleString()}</time></div>{message.sanitizedHtml ? <div className="admin-message-html" dangerouslySetInnerHTML={{ __html: message.sanitizedHtml }} /> : <p className="admin-message-text">{message.textBody}</p>}<p className="admin-message-status">{message.direction === "outbound" && <><Send size={12} /> {message.status}</>}</p></article>)}</div><div className="admin-composer"><strong>Reply to {latest?.fromAddress}</strong><textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="Write your reply…" /><div className="admin-composer-foot"><span>{status || "Drafts save automatically"}</span><button className="admin-primary" onClick={() => void send()} disabled={!body.trim() || status === "Sending…"}><Send size={14} /> Send</button></div></div></div>;
}

function NewComposer({ fromAddress, onClose }: { fromAddress: string; onClose: () => void }) {
  const [to, setTo] = useState(""); const [cc, setCc] = useState(""); const [bcc, setBcc] = useState(""); const [subject, setSubject] = useState(""); const [body, setBody] = useState(""); const [status, setStatus] = useState(""); const draftId = useRef<string | undefined>(undefined); const sendKey = useRef<string | undefined>(undefined);
  useEffect(() => { let cancelled = false; void fetch("/api/admin/inbox/drafts?unthreaded=true").then(async (response) => response.ok ? await response.json() as { drafts: Array<{ id: string; fromAddress: string; toAddresses: string[]; ccAddresses: string[]; bccAddresses: string[]; subject: string; textBody: string }> } : { drafts: [] }).then((data) => { const draft = data.drafts.find((item) => item.fromAddress === fromAddress); if (!cancelled && draft) { draftId.current = draft.id; setTo(draft.toAddresses.join(", ")); setCc(draft.ccAddresses.join(", ")); setBcc(draft.bccAddresses.join(", ")); setSubject(draft.subject); setBody(draft.textBody); } }); return () => { cancelled = true; }; }, [fromAddress]);
  useEffect(() => { const timer = window.setTimeout(async () => { const response = await fetch("/api/admin/inbox/drafts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: draftId.current, threadId: null, fromAddress, toAddresses: to ? [to] : [], ccAddresses: cc ? [cc] : [], bccAddresses: bcc ? [bcc] : [], subject, textBody: body }) }); if (response.ok) { draftId.current = (await response.json() as { draft?: { id: string } }).draft?.id; setStatus("Draft saved"); } }, 700); return () => window.clearTimeout(timer); }, [bcc, body, cc, fromAddress, subject, to]);
  async function send() { sendKey.current ??= crypto.randomUUID(); setStatus("Sending…"); const response = await fetch("/api/admin/inbox/send", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idempotencyKey: sendKey.current, draftId: draftId.current ?? null, fromAddress, to, cc, bcc, subject, textBody: body }) }); setStatus(response.ok ? "Sent" : "Could not send"); if (response.ok) { draftId.current = undefined; sendKey.current = undefined; onClose(); } }
  return <div className="admin-thread-content"><div className="admin-thread-toolbar"><button className="admin-icon-button admin-mobile-only" aria-label="Close composer" onClick={onClose}><ChevronLeft size={18} /></button><div className="admin-toolbar-actions"><span className="admin-muted">New message</span></div></div><div className="admin-thread-heading"><p className="eyebrow">From {fromAddress}</p><h2>Start a conversation</h2></div><div className="admin-composer admin-composer-new"><label>To<input value={to} onChange={(event) => setTo(event.target.value)} placeholder="customer@example.com" /></label><label>CC<input value={cc} onChange={(event) => setCc(event.target.value)} placeholder="Optional" /></label><label>BCC<input value={bcc} onChange={(event) => setBcc(event.target.value)} placeholder="Optional" /></label><label>Subject<input value={subject} onChange={(event) => setSubject(event.target.value)} placeholder="Subject" /></label><textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="Write your message…" /><div className="admin-composer-foot"><span>{status || "Drafts save automatically"}</span><button className="admin-primary" onClick={() => void send()} disabled={!to.trim() || !body.trim() || status === "Sending…"}><Send size={14} /> Send</button></div></div></div>;
}
