import { sql } from "drizzle-orm";
import { AnyPgColumn, boolean, check, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

export const campaignRuns = pgTable("campaign_runs", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  cohort: text("cohort").notNull(),
  hypothesis: text("hypothesis").notNull(),
  channel: text("channel").notNull().default("manual_zoho_browser"),
  state: text("state").notNull().default("planned"),
  responseCheckDueAt: timestamp("response_check_due_at", { withTimezone: true }).notNull(),
  clientRequestId: text("client_request_id"),
  createdBy: text("created_by").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  check("campaign_runs_channel_check", sql`${table.channel} = 'manual_zoho_browser'`),
  check("campaign_runs_state_check", sql`${table.state} IN ('planned', 'active', 'closed', 'retrospected')`),
  uniqueIndex("campaign_runs_request_unique").on(table.clientRequestId),
  index("campaign_runs_due_state_idx").on(table.state, table.responseCheckDueAt),
]);

export const campaignObservations = pgTable("campaign_observations", {
  id: text("id").primaryKey(),
  campaignId: text("campaign_id").notNull().references(() => campaignRuns.id),
  eventType: text("event_type").notNull(),
  source: text("source").notNull().default("manual_zoho_browser"),
  outcome: text("outcome").notNull(),
  attribution: text("attribution").notNull().default("unknown"),
  quantity: integer("quantity").notNull().default(1),
  observedAt: timestamp("observed_at", { withTimezone: true }).notNull(),
  checkedFolders: jsonb("checked_folders").$type<string[]>().notNull().default([]),
  checkedSentObservationIds: jsonb("checked_sent_observation_ids").$type<string[]>().notNull().default([]),
  resolvesObservationId: text("resolves_observation_id").references((): AnyPgColumn => campaignObservations.id),
  resolutionStatus: text("resolution_status"),
  visibleMessageId: text("visible_message_id"),
  variantId: text("variant_id"),
  note: text("note"),
  clientRequestId: text("client_request_id").notNull(),
  createdBy: text("created_by").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  check("campaign_observations_source_check", sql`${table.source} = 'manual_zoho_browser'`),
  check("campaign_observations_event_type_check", sql`${table.eventType} IN ('approved_variant', 'sent', 'send_resolution', 'delivered', 'bounce', 'reply', 'qualified_reply', 'opt_out', 'booked', 'attended', 'follow_up', 'close_out', 'response_check')`),
  check("campaign_observations_outcome_check", sql`${table.outcome} IN ('verified', 'no_reply_observed', 'unavailable', 'unverified')`),
  check("campaign_observations_attribution_check", sql`${table.attribution} IN ('attributable', 'unattributed', 'unknown')`),
  check("campaign_observations_quantity_check", sql`${table.quantity} BETWEEN 0 AND 10000`),
  check("campaign_observations_no_reply_folders_check", sql`${table.outcome} <> 'no_reply_observed' OR (${table.eventType} = 'response_check' AND ${table.checkedFolders} ?& ARRAY['inbox', 'spam'])`),
  check("campaign_observations_no_reply_sent_set_check", sql`${table.outcome} <> 'no_reply_observed' OR (${table.checkedFolders} ? 'sent' AND jsonb_array_length(${table.checkedSentObservationIds}) > 0)`),
  check("campaign_observations_approved_variant_check", sql`${table.eventType} <> 'approved_variant' OR (${table.outcome} = 'verified' AND ${table.attribution} = 'unknown' AND ${table.quantity} = 0 AND ${table.visibleMessageId} IS NOT NULL AND ${table.variantId} IS NOT NULL AND ${table.variantId} ~ '^[A-Fa-f0-9]{64}$' AND ${table.note} IS NOT NULL)`),
  check("campaign_observations_verified_sent_check", sql`${table.eventType} <> 'sent' OR ${table.outcome} <> 'verified' OR (${table.visibleMessageId} IS NOT NULL AND ${table.variantId} IS NOT NULL AND ${table.variantId} ~ '^[A-Fa-f0-9]{64}$')`),
  check("campaign_observations_send_resolution_check", sql`${table.eventType} <> 'send_resolution' OR (${table.outcome} = 'verified' AND ${table.attribution} = 'unknown' AND ${table.quantity} = 0 AND ${table.resolvesObservationId} IS NOT NULL AND ${table.resolutionStatus} IS NOT NULL AND ${table.resolutionStatus} IN ('verified_sent', 'verified_not_sent') AND ${table.visibleMessageId} IS NOT NULL AND ${table.variantId} IS NOT NULL AND ${table.variantId} ~ '^[A-Fa-f0-9]{64}$' AND ${table.note} IS NOT NULL AND ((${table.resolutionStatus} = 'verified_sent' AND ${table.checkedFolders} ? 'sent') OR (${table.resolutionStatus} = 'verified_not_sent' AND ${table.checkedFolders} ?& ARRAY['sent', 'outbox', 'drafts'])))`),
  check("campaign_observations_send_resolution_fields_check", sql`${table.eventType} = 'send_resolution' OR (${table.resolvesObservationId} IS NULL AND ${table.resolutionStatus} IS NULL)`),
  check("campaign_observations_attribution_ref_check", sql`${table.attribution} <> 'attributable' OR ${table.eventType} = 'response_check' OR ${table.outcome} = 'unavailable' OR ${table.visibleMessageId} IS NOT NULL`),
  uniqueIndex("campaign_observations_request_unique").on(table.clientRequestId),
  uniqueIndex("campaign_observations_message_event_unique").on(table.visibleMessageId, table.eventType).where(sql`${table.visibleMessageId} IS NOT NULL`),
  uniqueIndex("campaign_observations_resolves_unique").on(table.resolvesObservationId).where(sql`${table.resolvesObservationId} IS NOT NULL`),
  index("campaign_observations_campaign_time_idx").on(table.campaignId, table.observedAt),
]);

export const campaignLearningActions = pgTable("campaign_learning_actions", {
  id: text("id").primaryKey(),
  campaignId: text("campaign_id").notNull().references(() => campaignRuns.id),
  hypothesis: text("hypothesis").notNull(),
  action: text("action").notNull(),
  expectedMetric: text("expected_metric").notNull(),
  comparableSignals: integer("comparable_signals").notNull(),
  relevantRecords: integer("relevant_records").notNull(),
  risk: text("risk").notNull(),
  status: text("status").notNull().default("proposed"),
  result: text("result"),
  implementationReference: text("implementation_reference"),
  measurementWindowStartAt: timestamp("measurement_window_start_at", { withTimezone: true }),
  measurementWindowEndAt: timestamp("measurement_window_end_at", { withTimezone: true }),
  measurementCheckpointAt: timestamp("measurement_checkpoint_at", { withTimezone: true }),
  rationale: text("rationale"),
  evidenceRefs: jsonb("evidence_refs").$type<string[]>(),
  supportingObservationIds: jsonb("supporting_observation_ids").$type<string[]>().notNull().default([]),
  decision: text("decision"),
  clientRequestId: text("client_request_id"),
  userDecisionApproved: boolean("user_decision_approved").notNull().default(false),
  createdBy: text("created_by").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  check("campaign_learning_actions_risk_check", sql`${table.risk} IN ('low', 'high')`),
  check("campaign_learning_actions_status_check", sql`${table.status} IN ('proposed', 'applied', 'needs_user_decision', 'user_approved', 'rejected', 'evaluated')`),
  check("campaign_learning_actions_signal_counts_check", sql`${table.comparableSignals} >= 0 AND ${table.relevantRecords} >= 0`),
  check("campaign_learning_actions_apply_gate", sql`${table.status} NOT IN ('applied', 'evaluated') OR (${table.risk} = 'low' AND (${table.comparableSignals} >= 3 OR ${table.relevantRecords} >= 10)) OR (${table.risk} = 'high' AND ${table.userDecisionApproved})`),
  check("campaign_learning_actions_high_risk_decision_check", sql`${table.risk} <> 'high' OR ${table.status} NOT IN ('applied', 'evaluated') OR ${table.userDecisionApproved}`),
  check("campaign_learning_actions_reference_check", sql`${table.status} NOT IN ('applied', 'evaluated') OR ${table.implementationReference} IS NOT NULL`),
  check("campaign_learning_actions_result_check", sql`${table.status} <> 'evaluated' OR ${table.result} IS NOT NULL`),
  uniqueIndex("campaign_learning_actions_request_unique").on(table.clientRequestId),
  index("campaign_learning_actions_campaign_idx").on(table.campaignId, table.createdAt),
]);

export const campaignLearningActionEvents = pgTable("campaign_learning_action_events", {
  id: text("id").primaryKey(),
  actionId: text("action_id").notNull().references(() => campaignLearningActions.id),
  eventKind: text("event_kind").notNull(),
  previousStatus: text("previous_status"),
  status: text("status").notNull(),
  rationale: text("rationale").notNull(),
  evidenceRefs: jsonb("evidence_refs").$type<string[]>().notNull().default([]),
  decision: text("decision").notNull(),
  implementationReference: text("implementation_reference"),
  result: text("result"),
  requestPayload: jsonb("request_payload").$type<Record<string, unknown> | null>(),
  clientRequestId: text("client_request_id").notNull(),
  createdBy: text("created_by").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  check("campaign_learning_action_events_kind_check", sql`${table.eventKind} IN ('created', 'transition', 'migration_snapshot')`),
  check("campaign_learning_action_events_status_check", sql`${table.status} IN ('proposed', 'applied', 'needs_user_decision', 'user_approved', 'rejected', 'evaluated')`),
  uniqueIndex("campaign_learning_action_events_request_unique").on(table.clientRequestId),
  index("campaign_learning_action_events_action_time_idx").on(table.actionId, table.createdAt),
]);
